CREATE TABLE practitioners (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name TEXT NOT NULL,
    credentials JSONB DEFAULT '[]'::jsonb,
    specialty_areas JSONB DEFAULT '[]'::jsonb,
    practice_name TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT,
    phone TEXT,
    email TEXT,
    website TEXT,
    insurance_accepted TEXT,
    languages JSONB DEFAULT '["English"]'::jsonb,
    years_of_experience INTEGER,
    bio TEXT,
    rating NUMERIC(3,2),
    review_count INTEGER DEFAULT 0,
    photo_url TEXT,
    is_featured BOOLEAN DEFAULT false,
    telehealth_available BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);