CREATE TABLE provider_submissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    full_name TEXT NOT NULL,
    credentials TEXT,
    specialty_areas TEXT[],
    practice_name TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    zip_code TEXT,
    phone TEXT,
    email TEXT,
    website TEXT,
    insurance_accepted TEXT,
    languages TEXT[],
    years_of_experience INTEGER,
    bio TEXT,
    photo_url TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending',
    'approved',
    'rejected')),
    submitted_at TIMESTAMPTZ DEFAULT NOW()
);